
version: '2'
volumes: 
    user_data:
    user_data_2:
services:
  freqtrade:
    build: .
    privileged: true
    restart: unless-stopped
    container_name: freqtrade
    volumes:
      - "user_data:/freqtrade/user_data"
    expose: 
      - "8080"
    entrypoint: /bin/bash
    command: /freqtrade/run.sh doge.json Pump TELEGRAM_TOKEN BINANCE_KEY BINANCE_SECRET
    # Uncomment to disable starting freqtrade
    #entrypoint: tail
    #command: -f /dev/null
  freqtrade_2:
    build: .
    privileged: true
    restart: unless-stopped
    container_name: freqtrade_2
    volumes:
      - "user_data_2:/freqtrade/user_data"
    entrypoint: /bin/bash
    command: /freqtrade/run.sh pump.json FastPump TELEGRAM_TOKEN_2 BINANCE_KEY BINANCE_SECRET
  twithook:
    build: ./twithook
    command: /twithook.sh
  tghook:
    build: ./tghook
    command: /tghook.sh
  